Whisper.net/Internals/Native/Data.cs
Whisper.net/Internals/Native/NativeMethods.cs

The newest whisper.cpp introduced some breaking changes in WhisperFullParams (Why they felt the need to add them here and break every other implementation for a debug variable is beyond me). This bumps the underlying dependency and adds the new APIs to the NativeMethods.cs

Bump whisper.cpp and address breaking changes

---

.gitignore
runtimes/Whisper.net.Runtime.CoreML/Whisper.net.Runtime.CoreML.targets
runtimes/Whisper.net.Runtime.Vulkan/Whisper.net.Runtime.Vulkan.targets

This pull request includes several updates to the build configurations for the Whisper.net runtime, specifically targeting different platforms and frameworks. The most important changes involve adding support for Metal and Vulkan assets and ensuring proper handling of these assets across various platforms.
* [`runtimes/Whisper.net.Runtime.CoreML/Whisper.net.Runtime.CoreML.targets`](diffhunk://#diff-43931768d430a4d2f29c47b1d3745781ad50e92fcf78eb782952e58100f45e40L106-R121): Added conditions to include the `ggml-metal.metal` asset for maccatalyst, iOS, tvOS, and their simulators, and ensured the asset is copied correctly for MacOS targets.
* [`runtimes/Whisper.net.Runtime.Vulkan/Whisper.net.Runtime.Vulkan.targets`](diffhunk://#diff-06af01bfa48360bebc6c9fc706d493cab542edb77a60f7c921454c664432 …

Fixed vulkan and coreml targets

---

Whisper.net/LibraryLoader/ILibraryLoader.cs
Whisper.net/LibraryLoader/LinuxLibraryLoader.cs
Whisper.net/LibraryLoader/MacOsLibraryLoader.cs
Whisper.net/LibraryLoader/NativeLibraryLoader.cs
Whisper.net/LibraryLoader/UniversalLibraryLoader.cs
Whisper.net/LibraryLoader/WindowsLibraryLoader.cs
examples/NvidiaCuda/NvidiaCuda.csproj

This pull request includes several changes to the `Whisper.net` library, primarily focusing on simplifying the `OpenLibrary` method across different platform-specific implementations and updating project references in the NvidiaCuda example.
* [`Whisper.net/LibraryLoader/ILibraryLoader.cs`](diffhunk://#diff-718393293ccb9db83b46a36995bfbfffd5063fe060cd43948cc944ec3a2a28adL7-R7): Removed the `global` parameter from the `OpenLibrary` method in the `ILibraryLoader` interface.
* [`Whisper.net/LibraryLoader/LinuxLibraryLoader.cs`](diffhunk://#diff-7c1a9b168c032a8ba88187e5e56c96a21bfb270ba866a73d3f4b717f5eed6f9dL21-R30): Updated the `OpenLibrary` method to remove the `global` parameter and always use the `0x00102` flag.
* [`Whisper.net/LibraryLoader/MacOsLibraryLoader.cs`](diffhunk://#diff-94d9ea …

Removed unused param and direct reference in cuda sample

---

Makefile
Whisper.net/Internals/Native/INativeWhisper.cs
Whisper.net/Internals/Native/Implementations/DllImportsNativeLibWhisper.cs
Whisper.net/Internals/Native/Implementations/DllImportsNativeWhisper.cs
Whisper.net/Internals/Native/Implementations/LibraryImportInternalWhisper.cs
Whisper.net/Internals/Native/Implementations/LibraryImportLibWhisper.cs
Whisper.net/Internals/Native/Implementations/NativeLibraryWhisper.cs
Whisper.net/WhisperFactory.cs

This pull request includes several changes to the `Makefile` to enable native optimizations and updates to the `INativeWhisper` interface and its implementations to support a new method for printing system information.
* Added the `-DGGML_NATIVE=ON` flag to various build configurations in the `Makefile` to enable native optimizations. (`Makefile`) [[1]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L55-R79) [[2]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L111-R111) [[3]](diffhunk://#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L170-R178)
* Introduced a new delegate `whisper_print_system_info` in the `INativeWhisper` interface to allow printing system information. …

Fixed the perf issue on linux

---

.github/workflows/push-all.yml
Whisper.net/Whisper.net.csproj
examples/BlazorApp/BlazorApp.Client/BlazorApp.Client.csproj
examples/ContinuousRecognition/ContinuousRecognition.csproj
examples/CoreML/CoreML.csproj
examples/Diarization/Diarization.csproj
examples/MultiRuntime/MultiRuntime.csproj
examples/NAudioMp3/NAudioMp3.csproj
examples/NAudioResampleWav/NAudioResampleWav.csproj
examples/NvidiaCuda/NvidiaCuda.csproj
examples/OpenVinoExample/OpenVinoExample.csproj
examples/ParallelExecution/ParallelExecution.csproj
examples/Simple/Simple.csproj
examples/SimpleSync/SimpleSync.csproj
examples/Vulkan/Vulkan.csproj
readme.md

This pull request includes version updates for the `Whisper.net` package and its associated runtime packages across various project files and documentation. The updates ensure consistency and compatibility with the latest release.
* [`Whisper.net/Whisper.net.csproj`](diffhunk://#diff-1e6efca4d3eb5af047dd5e0628fad7df48807ca5628f85866b69ec30c5a083d8L7-R7): Updated the `Whisper.net` package version from `1.7.1` to `1.7.2`. (for newer version of previews)
* Various example projects (`BlazorApp`, `ContinuousRecognition`, `CoreML`, `Diarization`, `MultiRuntime`, `NAudioMp3`, `NAudioResampleWav`, `NvidiaCuda`, `OpenVinoExample`, `ParallelExecution`, `Simple`, `SimpleSync`, `Vulkan`):
* Updated `Whisper.net` and `Whisper.net.Runtime` package versions from `1.7.0` to `1.7.1`. …

Versions bumped after release

---

readme.md

In the README.md, the example to change the runtime order is missing `.Instance` and also the parameter should be a List and not an array in order to compile.

Fix RuntimeOptions example

---

Whisper.net/LibraryLoader/CudaHelper.cs
Whisper.net/LibraryLoader/NativeLibraryLoader.cs
Whisper.net/Logger/LogProvider.cs
tests/Whisper.net.Tests/FactoryTests.cs

This pull request introduces logging enhancements to improve debugging capabilities in the `Whisper.net` library. The changes primarily involve adding debug log statements to track the flow and status of library loading processes.
* [`Whisper.net/LibraryLoader/CudaHelper.cs`](diffhunk://#diff-feaf6c698ad5f5efcfdd4abf24d4fefd72e86b534e20403fef47e50884ca5267R6-R13): Added debug log statements to track CUDA availability checks and library loading status. [[1]](diffhunk://#diff-feaf6c698ad5f5efcfdd4abf24d4fefd72e86b534e20403fef47e50884ca5267R6-R13) [[2]](diffhunk://#diff-feaf6c698ad5f5efcfdd4abf24d4fefd72e86b534e20403fef47e50884ca5267R25) [[3]](diffhunk://#diff-feaf6c698ad5f5efcfdd4abf24d4fefd72e86b534e20403fef47e50884ca5267R40-R44)
* …

Added logs for lib loading

---

Whisper.net/WhisperFactory.cs
tests/Whisper.net.Tests/FactoryTests.cs

Added GetSupportedLanguages method

---

.github/workflows/windows-noavx-native-build.yml
Makefile
Whisper.net/LibraryLoader/NativeLibraryLoader.cs
readme.md
runtimes/Whisper.net.Runtime.NoAvx/Whisper.net.Runtime.NoAvx.targets
windows-scripts.ps1

I was using -DGGML_NATIVE=ON before which was just using all the instructions available on the build machine (including F16C).
Once I removed it during https://github.com/sandrohanea/whisper.net/commit/5ddb2c7810e100b71bf70f576bd6a76bfa56cb16 it started to be a lot slower.
F16C instruction is utilized heavily during CPU inference.

Fixed linux performance by adding F16C to list of required specialized instructions.

---

Whisper.net/WhisperFactory.cs

Fixing #256 
This pull request includes changes to the `Whisper.net/WhisperFactory.cs` file to improve the handling of the initialization state and disposal logic of the `WhisperFactory` class. The most important changes are the addition of a new field to track if the factory was eagerly initialized and adjustments to the disposal logic to account for this state.
Initialization and disposal improvements:
* [`Whisper.net/WhisperFactory.cs`](diffhunk://#diff-d5e496f04b45a146de7fffa6b94601c9914d63fcedb85624efbcb96b7a5cbbeaR20): Added a new private readonly field `isEagerlyInitialized` to track whether the factory was eagerly initialized.
* [`Whisper.net/WhisperFactory.cs`](diffhunk://#diff-d5e496f04b45a146de7fffa6b94601c9914d63fcedb85624efbcb96b7a5cbbeaR41): Set `isEagerlyInitialized` to …

Fixed the issue with the eager init context that is not freeing memory.

---

Whisper.net/Internals/Native/Implementations/LibraryImportInternalWhisper.cs

Fixes [issue](https://github.com/sandrohanea/whisper.net/issues/178) with `System.DllNotFoundException: __Internal` on iOS devices.

Fix static linking for iOS

---

.github/workflows/dotnet-maui.yml
.github/workflows/dotnet.yml
.github/workflows/windows-native-build.yml
Directory.Packages.props
Whisper.net.Demo/Whisper.net.Demo.csproj
Whisper.net/Internals/Native/Implementations/LibraryImportInternalWhisper.cs
Whisper.net/Whisper.net.csproj
examples/BlazorApp/BlazorApp.Client/BlazorApp.Client.csproj
examples/BlazorApp/BlazorApp/BlazorApp.csproj
examples/ContinuousRecognition/ContinuousRecognition.csproj
examples/CoreML/CoreML.csproj
examples/Diarization/Diarization.csproj
examples/Diarization/Program.cs
examples/MultiRuntime/MultiRuntime.csproj
examples/NAudioMp3/NAudioMp3.csproj
examples/NAudioResampleWav/NAudioResampleWav.csproj
examples/NvidiaCuda/NvidiaCuda.csproj
examples/OpenVinoExample/OpenVinoExample.csproj
examples/ParallelExecution/ParallelExecution.csproj
examples/Simple/Simple.csproj
examples/SimpleSync/SimpleSync.csproj
examples/Vulkan/Vulkan.csproj
tests/Whisper.net.Maui.Tests/Whisper.net.Maui.Tests.csproj
tests/Whisper.net.Tests/Whisper.net.Tests.csproj

This pull request includes several updates to upgrade the project to use .NET 9.0 and update various package versions. The most important changes include updating the .NET version in multiple project files and workflows, as well as updating package versions in the `Directory.Packages.props` file.
* Updated the .NET version from `8.0.x` to `9.0.x` in the `.github/workflows/dotnet-maui.yml` file.
* Updated the .NET version from `8.0.x` and `6.0.x` to `9.0.x` in the `.github/workflows/dotnet.yml` file. [[1]](diffhunk://#diff-d5a2cea578a0446aad66faf31bf1076ae94c9916b1a3374e342272a6300e8344L21-R21) [[2]](diffhunk://#diff-d5a2cea578a0446aad66faf31bf1076ae94c9916b1a3374e342272a6300e8344L51-R51) [[3]](diffhunk://#diff-d5a2cea578a0446aad66faf31bf1076ae94c9916b1a3374e342272a6300e8344L81-R81)
* …

Bumped versions

---

.github/workflows/release.yml

This pull request includes updates to the `.github/workflows/release.yml` file to add new build jobs and reorder existing ones. The most important changes include adding a new build job for Linux with Vulkan, reordering the list of jobs, and ensuring that the `windows-no-avx` job is correctly positioned.
* Added a new job for Linux with Vulkan (`linux-vulkan`) that runs conditionally based on the `BuildGpuLibs` input.
* Reordered the list of jobs to ensure correct execution order and fixed the positioning of the `windows-no-avx` job.

Fixing nuget vulkan

---

Whisper.net/Ggml/GgmlType.cs
Whisper.net/Internals/ModelLoader/WhisperProcessorModelBufferLoader.cs
Whisper.net/Internals/ModelLoader/WhisperProcessorModelFileLoader.cs
Whisper.net/LibraryLoader/RuntimeOptions.cs

This PR adds the ability to configure a custom attention heads array to enable DTW time alignment when using non-standard Whisper models which don't have a named preset configured in WhisperAlignmentHeadsPreset enumeration. The standard models have these presets included in whisper.cpp but for any other model you must specify the model-specific values.
For example, for the model "Distil Large V3", you need to use use:
```
RuntimeOptions.Instance.SetUseDtwTimeStamps(true);
RuntimeOptions.Instance.SetHeadsPreset(WhisperAlignmentHeadsPreset.Custom);
RuntimeOptions.Instance.SetAlignmentHeads(
Enumerable.Range(0, 20).Select(i => new WhisperAlignmentHead(1, i)).ToArray()
);
```
This one seems simple (array where TextLayer is always 1, and Head is 0...19), but that isn't the case for every …

Support setting custom alignment heads for dtw

---

Whisper.net/Ggml/GgmlType.cs
Whisper.net/Internals/ModelLoader/ModelLoaderUtils.cs
Whisper.net/Internals/ModelLoader/WhisperProcessorModelBufferLoader.cs
Whisper.net/Internals/ModelLoader/WhisperProcessorModelFileLoader.cs
Whisper.net/Internals/Native/Data.cs
Whisper.net/LibraryLoader/RuntimeOptions.cs
Whisper.net/WhisperAlignmentHeads.cs
Whisper.net/WhisperFactory.cs
Whisper.net/WhisperFactoryOptions.cs

As the options for creating a WhisperFactory were growing, took the initiative to migrate some of the options that are reusable to WhisperFactoryOptions and removing them from RuntimeOptions.
Now, RuntimeOptions remains only for Library loading (whisper.cpp Runtime) and any other options like GPU device, DTW options, etc. can be defined for each factory independent on the library itself.

Added Whisper Factory Options

---

.github/workflows/dotnet.yml
Whisper.net/LibraryLoader/CudaHelper.cs
Whisper.net/LibraryLoader/NativeLibraryLoader.cs
Whisper.net/LibraryLoader/RuntimeOptions.cs
Whisper.net/Logger/LogProvider.cs
Whisper.net/Logger/WhisperLogger.cs
Whisper.net/WhisperProcessor.cs
examples/CoreML/Program.cs
examples/MultiRuntime/Program.cs
examples/NvidiaCuda/Program.cs
examples/OpenVinoExample/Program.cs
examples/ParallelExecution/Program.cs
examples/Simple/Program.cs
examples/SimpleSync/Program.cs
examples/Vulkan/Program.cs
readme.md
tests/Whisper.net.Tests/FactoryTests.cs

This pull request includes several changes to improve logging and workflow behavior. The most important changes involve replacing the `LogProvider` with `WhisperLogger` and ensuring that test result files are uploaded regardless of test success or failure.
* Replaced instances of `LogProvider.Log` with `WhisperLogger.Log` in `CudaHelper.cs`, `NativeLibraryLoader.cs`, and `RuntimeOptions.cs` to standardize logging. [[1]](diffhunk://#diff-feaf6c698ad5f5efcfdd4abf24d4fefd72e86b534e20403fef47e50884ca5267L13-R13) [[2]](diffhunk://#diff-ff57ed519e83a61fa2d11b0278481279c8298ae4836d4a90c271cc5ca372c5eaL19-R33) [[3]](diffhunk://#diff-ff57ed519e83a61fa2d11b0278481279c8298ae4836d4a90c271cc5ca372c5eaL90-R113) [[4]](diffhunk://#diff-ff57ed519e83a61fa2d11b0278481279c8298ae4836d4a90c271cc5ca372c5eaL146-R …

Removed unnecessary instances and simplified LogProviders + RuntimeOptions

---

Whisper.net/LibraryLoader/LibdlLibraryLoader.cs

This issue is reproducing if netstandard version is used on systems that have only `libdl.so.2` without a symlink to `libdl.so`. 
Netstandard version can be used if the library is referenced in a netstandard package first, or when netframework is used (with mono, for libdl to be needed). For dotnet 8+ UniversalLibraryLoader is being used that handles this more gracefully.

Fixed libdl.so.2 issue

---

Directory.Packages.props

Fluent Assertion changed their licensing method. It will be removed in future work, but for now, keeping the old Apache2 version.
Even if the usage will be for non-commercial purposes in this OS library, I do not indorse open-source software that change their license for newer versions.

Reverted auto-commit for FluentAssertion bump by dependabot

---

Whisper.net/IStringPool.cs
Whisper.net/Internals/StringPool.cs
Whisper.net/WhisperFactory.cs
Whisper.net/WhisperProcessor.cs
Whisper.net/WhisperProcessorBuilder.cs
Whisper.net/WhisperProcessorOptions.cs
examples/LowAllocationStringPooling/LowAllocationStringPooling.csproj
examples/LowAllocationStringPooling/Program.cs
examples/Whisper.net.Examples.sln

This PR enhances the string pooling mechanism in `Whisper.net` to optimize memory usage and reduce allocations when handling strings, particularly in high-performance scenarios. The changes focus on refining how strings are pooled, retrieved, and returned, ensuring efficient reuse.
- Implemented `StringPool` to manage and reuse strings, reducing memory pressure.
- Optimized UTF8 string conversion using pooled strings to avoid unnecessary allocations.
- Introduced `ReturnString` to correctly reinsert strings into the pool for future reuse.
- Integrated `StringPool` usage across `WhisperProcessor` where applicable.
- Ensured thread safety and performance by structuring the pool using `SortedList<int, Stack<string>>`.
- Added example of how to use default string pool.
- **Lower GC …

Added string pooling feature

---

.github/workflows/build-all.yml
.github/workflows/dotnet-noavx.yml
Whisper.net.Demo/Whisper.net.Demo.csproj
Whisper.net.sln
Whisper.net/Whisper.net.csproj
examples/BlazorApp/BlazorApp.Client/BlazorApp.Client.csproj
examples/ContinuousRecognition/ContinuousRecognition.csproj
examples/CoreML/CoreML.csproj
examples/CoreML/Program.cs
examples/Diarization/Diarization.csproj
examples/LowAllocationStringPooling/LowAllocationStringPooling.csproj
examples/MultiRuntime/MultiRuntime.csproj
examples/NAudioMp3/NAudioMp3.csproj
examples/NAudioResampleWav/NAudioResampleWav.csproj
examples/NvidiaCuda/NvidiaCuda.csproj
examples/OpenVinoExample/OpenVinoExample.csproj
examples/OpenVinoExample/Program.cs
examples/ParallelExecution/ParallelExecution.csproj
examples/Simple/Simple.csproj
examples/SimpleSync/SimpleSync.csproj
examples/Vulkan/Vulkan.csproj
readme.md
tests/Whisper.net.Tests/Whisper.net.Tests.csproj
tools/WhisperNetDependencyChecker/Program.cs
tools/WhisperNetDependencyChecker/WhisperNetDependencyChecker.csproj
windows-scripts.ps1

Updated all example projects to use Whisper.net and relevant runtime packages version 1.8.0. Adjusted code to use the new `WhisperGgmlDownloader.Default` API for model downloads and manifest file retrieval. Incremented the library version to 1.8.1-preview1 in the main project.

Preparing 1.8.1

---

Directory.Packages.props
Whisper.net.Demo/Program.cs
Whisper.net.Demo/Whisper.net.Demo.csproj
Whisper.net.Demo/Whisper.net.Demo.sln
Whisper.net/Internals/Native/INativeCuda.cs
Whisper.net/LibraryLoader/NativeLibraryLoader.cs
Whisper.net/LibraryLoader/UniversalLibraryLoader.cs
Whisper.net/SpeechToTextClient/SpeechToTextOptionsExtensions.cs
Whisper.net/SpeechToTextClient/WhisperSpeechToTextClient.cs
Whisper.net/Whisper.net.csproj
Whisper.net/WhisperFactoryOptions.cs
nuget.config
tests/Whisper.net.Tests/ProcessAsyncFunctionalTests.cs
tests/Whisper.net.Tests/SegmentDataComparer.cs
tests/Whisper.net.Tests/SpeechToText/SpeechToTextOptionsExtensionsTests.cs
tests/Whisper.net.Tests/SpeechToText/WhisperSpeechToTextClientConstructorTests.cs
tests/Whisper.net.Tests/SpeechToText/WhisperSpeechToTextClientTest.cs
tools/WhisperNetDependencyChecker/DependencyWalker/INativeLibraryLoader.cs
tools/WhisperNetDependencyChecker/DependencyWalker/NativeLibraryChecker.cs

This implementation adds support to the latest `ISpeechToTextClient` abstraction from the `Microsoft.Extensions.AI.Abstractions` package.
- Updated Runtime version
- Added implementation for the client using same pattern `With` for adding options.
- Added Demo for the new client
- Minor warning fixes (blank lines, missing headers, unused usings)

Add ISpeechToTextClient implementation support

---

Whisper.net/WhisperProcessor.cs

The way the segment event handlers were being dispatched caused a rare exception if a new handler was added/removed by ProcessAsync:
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at Whisper.net.WhisperProcessor.OnNewSegment(IntPtr state)
at Whisper.net.WhisperProcessor.OnNewSegmentStatic(IntPtr ctx, IntPtr state, Int32 nNew, IntPtr userData)
This patch fixes the crash by preventing concurrent access to the collection.

Fixed concurrent collection access crash
